---
title: "Ireland Gomes"
---

I'm an economic analyst and aspiring economist holding an M.Sc Economics and B.S. Economics with minors in legal studies and mathematics, both from the University of Oregon. 

My work spans microeconomic theory, applied microeconomics, econometric theory, econometric applications, and machine learning. Within my applicative work, I draw on methods including difference-in-differences (DiD), two-way fixed effects (TWFE), event studies, regression discontinuity (RD), instrumental variables (IVs), penalized regression, debiased ML, and ensemble methods, among others. 

Areas of particular professional interest to me are forensic litigation, regulatory economics, program evaluation, policy analysis, quantitaive research & risk modeling. Alongside are my research interests that include industrial organization, labor economics, information economics, antitrust & competition, public economics, regulation, and policy. 


[irelandggomes@gmail.com](mailto:irelandggomes@gmail.com) | [LinkedIn](https://www.linkedin.com/in/ireland-gomes-3b6581276)




